#This is the information about your stash instance
[Stash_Host]
#The scheme (either http or https)
Scheme = http
#The full hostname for your stash instance.  If you're running in docker you might want the
#service name and not localhost here.
Host = 192.168.1.88
#The port number for your stash instance
Port = 6973
#The api key, if your stash instance is password protected
ApiKey =

[QBittorent_Host]
#The full hostname for your qbittorrent instance.  If you're running in docker you might want the
#service name and not localhost here.
Host = 192.168.1.88
#The port number for your qbittorrent instance
Port = 8080
#The username, if your stash qbittorrent is password protected
username = admin
#The password, if your stash qbittorrent is password protected
password = admin

[ProxiedScaper]
Url = https://nyaa.si/?p=
Column_magnet = 2
Column_title = 1
Link_number = 1
Port = 55101
Interval = 30

[Path]
# Path to trash folder
Trash = /61.1_series/61.1.9.import/trash
Downloads = /downloads
Incomplete = /downloads/incomplete

[Scenes]
# Number of scenes to fetch
QueryMaxNumber = 400